# Generated by Django 4.2.4 on 2023-09-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matricula', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno_Walter_Sanchez',
            new_name='Alumno',
        ),
    ]
